#!/usr/bin/env bash
# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Backup the existing default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Define the redirection in the Nginx configuration file
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Check Nginx configuration for any syntax errors
sudo nginx -t

# Restart Nginx to apply the changes
sudo service nginx restart

