#!/usr/bin/env bash
#installing nginx and redirecting to another page

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/index.html'
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server/ a rewrite ^/redirect_me https://www.mbusa.com/en/vehicles/class/g-class/suv permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/ a error_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
