#!/usr/bin/env bash
#configuring my web-2 server to be like my web-01 server
apt-get update -y
apt-get install nginx -y

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
        listen 80;
        listen [::]:80 default_server;
        add_header X-served-By $HOSTNAME;

        root /etc/nginx/html;
        index index.html index.htm;

        location /redirect_me {
                return 301 http:cuberule.com/;
        }
        error_page 404 /404.html;
        location /404 {
                root /etc/nginx/html;
                internal;
        }
}" > /etc/nginx/sites-available/default
service nginx restart
