#!/usr/bin/env bash
#set the internal filed separator

IFS=':'
while read -r username x uid gid gecos homedir shell; do
	uid_info=$(grep -E "^$username:" /etc/passwd | cut -d ':' -f 5)
	passcode=$(echo "$x" | cut -c1)
	echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $uid_info"
done < /etc/passwd
