#!/usr/bin/env bash
# bash to print best school 10 times and display hi on the fourth
i=0;
while((i<10)); do
	if ((i==8)); then
		echo "Best School"
		echo "Hi"
	else
		echo "Best school"
	fi
	((i++))
done
