#!/usr/bin/env bash
# Commands used to fix the issue
#make the apche server returns hello world!
docker exec -it <container_id> /bin/bash

# Ensure Apache is installed and running
sudo apt-get update -y
sudo apt-get install apache2 -y
sudo /etc/init.d/apache2 start
sudo echo "Hello Holberton" | sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
