#!/usr/bin/env bash

# Update the Nginx configuration file
sed -i 's/user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen .*/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart

