#!/usr/bin/env bash
#shorthand method
sed -i 's/user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/g' /etc/nginx/sites-available/default
service nginx restart

